language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
env:
    - DJANGO=test_requirements/django-1.3.txt DB=sqlite
    - DJANGO=test_requirements/django-1.3.txt DB=mysql
    - DJANGO=test_requirements/django-1.3.txt DB=postgres
    - DJANGO=test_requirements/django-1.4.txt DB=sqlite
    - DJANGO=test_requirements/django-1.4.txt DB=mysql
    - DJANGO=test_requirements/django-1.4.txt DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS djangocms_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database djangocms_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS djangocms_test'; fi"
  
install:
    - pip install -q -r $DJANGO --use-mirrors
script:
    python runtests.py --db $DB --db_name djangocms_test
notifications:
    email:
        recipients:
          - digi@treepy.com
        on_success: never
        on_failure: always
    irc:
        - "irc.freenode.org#django-cms"
        - "irc.freenode.org#django-cms-sprint"

