language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.3
    - DJANGO=1.4
install:
    - pip install pip install -q -r test_requirements/django-$DJANGO.txt --use-mirrors
script:
    python runtests.py
notifications:
    email:
        recipients:
          - digi@treepy.com
        on_success: never
        on_failure: always
    irc:
        - "irc.freenode.org#django-cms"
        - "irc.freenode.org#django-cms-sprint"

